# CloudFlare Workers 配置文件

name = "sourceforge-proxy"
main = "sourceforge-proxy.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Workers 配置
[env.production]
name = "sourceforge-proxy"

[env.staging]
name = "sourceforge-proxy-staging"

# 环境变量
[vars]
ENVIRONMENT = "production"
VERSION = "1.0.0"

[[kv_namespaces]]
binding = "STATS_KV"
id = "your_id"
preview_id = "your_preview_id"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
